version: '3.8'
services:
  backend:
    container_name: backend
    command: 'npm run start-dev'
    build: ./backend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    command:
      - "--init-file=/data/db/init.sql"
    ports:
      - '3306:3306'
    volumes:
      - data:/data/db
      - ./mysql/init.sql:/data/db/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
volumes:
  data:
